# 선물 월물 고정 패치 — us_stocks.js 에 한 번만 적용합니다
import re, shutil, sys
p = "/root/app/us_stocks.js"
s = open(p, encoding="utf-8").read()
if "월물기호" in s:
    print("이미 적용되어 있습니다"); sys.exit(0)
m = list(re.finditer(r"async\s+function\s+fetchOne\s*\(\s*sym\s*\)\s*\{", s))
if len(m) != 1:
    print("fetchOne 을 정확히 하나 찾지 못했습니다 — 손대지 않았습니다:", len(m)); sys.exit(1)
shutil.copy(p, p + ".bak_roll")
s = s[:m[0].start()] + "async function fetchOne원본(sym) {" + s[m[0].end():]
s = s.rstrip() + "\n" + "\n// ── 선물 월물 고정 (롤오버 때 등락률 부풀림 막기) ─────────────\n// 야후의 ES=F 같은 연속 선물은 만기가 지나면 다음 월물로 갈아타는데,\n// 일봉 목록의 '어제' 칸에는 옛 월물 종가가 남아 있어 등락률이 부풀려집니다.\n// (9월물 → 12월물이면 금리 몇 달치만큼, WTI 는 월물 사이 가격 차만큼)\n// 그래서 선물은 '12월물' 처럼 월물을 콕 집어 받습니다. 같은 상품끼리 비교하니\n// 롤오버와 상관없이 맞고, 월물 기호가 안 되면 원래 방식으로 돌아갑니다.\nconst 월코드 = ['F','G','H','J','K','M','N','Q','U','V','X','Z'];   // 1~12월\n\nfunction 셋째금요일(y, m) {                 // m: 1~12\n  const d = new Date(Date.UTC(y, m - 1, 1));\n  const 첫금 = 1 + ((5 - d.getUTCDay() + 7) % 7);\n  return new Date(Date.UTC(y, m - 1, 첫금 + 14));\n}\nfunction 영업일빼기(d, n) {\n  const x = new Date(d);\n  while (n > 0) {\n    x.setUTCDate(x.getUTCDate() - 1);\n    const w = x.getUTCDay();\n    if (w !== 0 && w !== 6) n--;\n  }\n  return x;\n}\nfunction 영업일로(d) {                     // 주말이면 앞 금요일로\n  const x = new Date(d);\n  while (x.getUTCDay() === 0 || x.getUTCDay() === 6) x.setUTCDate(x.getUTCDate() - 1);\n  return x;\n}\nfunction 달말영업일(y, m) {                 // m 달의 마지막 영업일\n  return 영업일로(new Date(Date.UTC(y, m, 0)));\n}\nfunction 날더하기(d, n) { const x = new Date(d); x.setUTCDate(x.getUTCDate() + n); return x; }\n\nconst 선물표 = {\n  // 주가지수: 3·6·9·12월, 셋째 금요일 만기, 8일 전(롤 주간)에 다음 월물로\n  'ES=F':  { 앞: 'ES',  뒤: '.CME', 달: [3, 6, 9, 12], 넘김: (y, m) => 날더하기(셋째금요일(y, m), -8) },\n  'NQ=F':  { 앞: 'NQ',  뒤: '.CME', 달: [3, 6, 9, 12], 넘김: (y, m) => 날더하기(셋째금요일(y, m), -8) },\n  'YM=F':  { 앞: 'YM',  뒤: '.CBT', 달: [3, 6, 9, 12], 넘김: (y, m) => 날더하기(셋째금요일(y, m), -8) },\n  'RTY=F': { 앞: 'RTY', 뒤: '.CME', 달: [3, 6, 9, 12], 넘김: (y, m) => 날더하기(셋째금요일(y, m), -8) },\n  // WTI: 매달. 앞달 25일(영업일 아니면 그 전)에서 3영업일 전 만기, 그 2일 전에 넘김\n  'CL=F':  { 앞: 'CL', 뒤: '.NYM', 달: [1,2,3,4,5,6,7,8,9,10,11,12],\n             넘김: (y, m) => 날더하기(영업일빼기(영업일로(new Date(Date.UTC(y, m - 2, 25))), 3), -2) },\n  // 금: 거래가 몰리는 2·4·6·8·12월. 앞달 마지막 영업일(첫 인도통지일) 3일 전에 넘김\n  'GC=F':  { 앞: 'GC', 뒤: '.CMX', 달: [2, 4, 6, 8, 12],\n             넘김: (y, m) => 날더하기(달말영업일(y, m - 1), -3) },\n};\n\nfunction 월물기호(sym, 지금 = new Date()) {\n  const t = 선물표[sym];\n  if (!t) return null;\n  const 오늘 = new Date(Date.UTC(지금.getUTCFullYear(), 지금.getUTCMonth(), 지금.getUTCDate()));\n  for (let y = 오늘.getUTCFullYear(); y <= 오늘.getUTCFullYear() + 1; y++) {\n    for (const m of t.달) {\n      if (t.넘김(y, m) > 오늘) return `${t.앞}${월코드[m - 1]}${String(y).slice(2)}${t.뒤}`;\n    }\n  }\n  return null;\n}\n\nasync function fetchOne(sym) {\n  const 월물 = 월물기호(sym);\n  if (월물) {\n    try {\n      const q = await fetchOne원본(월물);\n      if (q && q.price != null && q.prevClose) return { ...q, contract: 월물 };\n    } catch (e) {}\n  }\n  return fetchOne원본(sym);\n}\n" + "\n"
open(p, "w", encoding="utf-8").write(s)
print("적용 완료 · 원본은 us_stocks.js.bak_roll")
